"""Matemium multi-agent lifecycle engine."""

from .coordinator import CoordinatorConfig, LifecycleCoordinator, run_lifecycle
from .critic import CoordinatorHaltError, MAX_CRITIC_RETRIES
from .debug import DEBUG_FILENAME, build_debug_payload, write_debug_log
from .models import (
    DecoupledArtifacts,
    LifecycleResult,
    ModelTier,
    Phase,
    PostProductionOutput,
    ProcessingMode,
    ProjectSession,
    TimingBlueprint,
    TokenLedger,
    TIER_MULTIPLIERS,
)
from .timing import (
    build_audio_blueprint,
    build_mute_blueprint,
    expected_audio_total_duration,
    expected_mute_total_duration,
    instantiate_timing_blueprint,
    parse_whisper_timing_blueprint,
    round_ms,
)
from .writer import (
    PatchAmbiguousError,
    PatchBlock,
    PatchNotFoundError,
    WriterResult,
    apply_patch,
    apply_patch_to_disk,
    apply_patches,
    apply_patches_on_disk,
    format_patch_block,
    format_patch_document,
    parse_patch_blocks,
    write_decoupled_project,
)

__all__ = [
    "CoordinatorConfig",
    "CoordinatorHaltError",
    "DEBUG_FILENAME",
    "DecoupledArtifacts",
    "LifecycleCoordinator",
    "LifecycleResult",
    "MAX_CRITIC_RETRIES",
    "ModelTier",
    "PatchAmbiguousError",
    "PatchBlock",
    "PatchNotFoundError",
    "Phase",
    "PostProductionOutput",
    "ProcessingMode",
    "ProjectSession",
    "TIER_MULTIPLIERS",
    "TimingBlueprint",
    "TokenLedger",
    "WriterResult",
    "apply_patch",
    "apply_patch_to_disk",
    "apply_patches",
    "apply_patches_on_disk",
    "format_patch_block",
    "format_patch_document",
    "build_audio_blueprint",
    "build_debug_payload",
    "build_mute_blueprint",
    "expected_audio_total_duration",
    "expected_mute_total_duration",
    "instantiate_timing_blueprint",
    "parse_patch_blocks",
    "parse_whisper_timing_blueprint",
    "round_ms",
    "run_lifecycle",
    "write_decoupled_project",
    "write_debug_log",
]