"""Matemium multi-agent lifecycle engine."""

from .coordinator import CoordinatorConfig, LifecycleCoordinator, run_lifecycle
from .critic import (
    CoordinatorHaltError,
    MAX_CRITIC_RETRIES,
    compile_project_via_sidecar,
    make_sidecar_compile_fn,
    run_critic_loop,
    sidecar_binary_available,
)
from .debug import DEBUG_FILENAME, build_debug_payload, write_debug_log
from .guard import (
    apply_guard_to_project,
    apply_guard_to_scenes_file,
    dsl_has_watermark,
    inject_watermark_if_needed,
    inject_watermark_to_scenes_source,
    should_apply_watermark,
    should_apply_watermark_for_session,
)
from .models import (
    AccountTier,
    DecoupledArtifacts,
    LifecycleResult,
    ModelTier,
    Phase,
    PostProductionOutput,
    ProcessingMode,
    ProjectSession,
    TimingBlueprint,
    TokenLedger,
    TIER_MULTIPLIERS,
)
from .timing import (
    build_audio_blueprint,
    build_mute_blueprint,
    expected_audio_total_duration,
    expected_mute_total_duration,
    instantiate_timing_blueprint,
    parse_whisper_timing_blueprint,
    round_ms,
)
from .writer import (
    PatchAmbiguousError,
    PatchBlock,
    PatchNotFoundError,
    WriterResult,
    apply_patch,
    apply_patch_to_disk,
    apply_patches,
    apply_patches_on_disk,
    format_patch_block,
    format_patch_document,
    parse_patch_blocks,
    write_decoupled_project,
)

__all__ = [
    "AccountTier",
    "CoordinatorConfig",
    "CoordinatorHaltError",
    "apply_guard_to_project",
    "apply_guard_to_scenes_file",
    "compile_project_via_sidecar",
    "DEBUG_FILENAME",
    "DecoupledArtifacts",
    "dsl_has_watermark",
    "inject_watermark_if_needed",
    "inject_watermark_to_scenes_source",
    "LifecycleCoordinator",
    "LifecycleResult",
    "make_sidecar_compile_fn",
    "MAX_CRITIC_RETRIES",
    "ModelTier",
    "should_apply_watermark",
    "should_apply_watermark_for_session",
    "PatchAmbiguousError",
    "PatchBlock",
    "PatchNotFoundError",
    "Phase",
    "PostProductionOutput",
    "ProcessingMode",
    "ProjectSession",
    "TIER_MULTIPLIERS",
    "TimingBlueprint",
    "TokenLedger",
    "WriterResult",
    "apply_patch",
    "apply_patch_to_disk",
    "apply_patches",
    "apply_patches_on_disk",
    "format_patch_block",
    "format_patch_document",
    "build_audio_blueprint",
    "build_debug_payload",
    "build_mute_blueprint",
    "expected_audio_total_duration",
    "expected_mute_total_duration",
    "instantiate_timing_blueprint",
    "parse_patch_blocks",
    "parse_whisper_timing_blueprint",
    "round_ms",
    "run_critic_loop",
    "run_lifecycle",
    "sidecar_binary_available",
    "write_decoupled_project",
    "write_debug_log",
]