from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Request

from ..config import settings
from ..deps import AuthUser, require_user
from ..models import ChatCompletionRequest, ChatCompletionResponse
from ..rate_limit import enforce_rate_limit
from ..services.llm import complete_chat
from ..services.llm_management import record_platform_usage
from ..services.supabase import get_supabase_service

router = APIRouter(tags=["chat"])


@router.post("/chat/completions", response_model=ChatCompletionResponse)
async def chat_completions(
    request: Request,
    body: ChatCompletionRequest,
    user: Annotated[AuthUser, Depends(require_user)],
) -> ChatCompletionResponse:
    """
    Secure LLM proxy.

    - use_personal_llm=True or user has stored key for llm_provider → BYO (user's key, we only proxy).
    - Otherwise → our platform pool. We log real cost and deduct priced credits.
    """
    await enforce_rate_limit(request, user.id, user.plan)

    use_personal = bool(body.use_personal_llm)
    provider = body.llm_provider

    # Resolve early to know the mode (without exposing key to client)
    supabase = get_supabase_service()
    personal = await supabase.get_user_personal_key(user.id, provider) if use_personal else None
    using_platform = not personal

    if using_platform and not settings.llm_stub:
        if not await supabase.has_sufficient_credits(user.id, 1):
            raise HTTPException(
                status_code=402,
                detail="Insufficient platform credits. Buy more tokens or configure your own LLM keys.",
            )

    if body.use_autonomous_agent:
        # Run autonomous agent loop asynchronously and return the final result
        async def async_generate_fn(history: list[dict[str, str]]) -> str:
            from ..models import ChatMessage
            req_messages = [ChatMessage(role=m["role"], content=m["content"]) for m in history]
            cloned_req = body.model_copy(update={"messages": req_messages})
            res = await complete_chat(
                cloned_req,
                user_id=user.id,
                provider=provider,
                use_personal=use_personal,
                model_override=body.model,
            )
            return res.message.content

        from matemium.agent.react_runner import ReActAgentRunner
        runner = ReActAgentRunner()

        user_prompt = body.messages[-1].content if body.messages else "Please refactor my scenes.py file"

        project_dir = None
        if body.project_id:
            from matemium.paths import discover_root
            project_dir = str(discover_root() / "projects" / body.project_id)

        # Run loop
        messages = await runner.run_loop_async(
            user_prompt=user_prompt,
            generate_fn=async_generate_fn,
            project_dir=project_dir,
        )

        final_assistant_msg = next(
            (m for m in reversed(messages) if m["role"] == "assistant"),
            {"content": "No response generated by agent."}
        )
        content = final_assistant_msg["content"]

        from ..services.llm import extract_code_edit
        code_edit = extract_code_edit(content)

        import uuid
        response = ChatCompletionResponse(
            id=f"chatcmpl-agent-{uuid.uuid4().hex[:12]}",
            message=ChatMessage(role="assistant", content=content),
            code_edit=code_edit,
            model=body.model or "agent-runner",
            stub=False,
        )
    else:
        response = await complete_chat(
            body,
            user_id=user.id,
            provider=provider,
            use_personal=use_personal,
            model_override=body.model,
        )

    try:
        await supabase.increment_ai_calls(user.id, 1)

        if using_platform and not settings.llm_stub:
            # Try to extract usage if the provider returned it in the (future enhanced) response
            usage_info = getattr(response, "usage", None) or {}
            await record_platform_usage(
                user_id=user.id,
                provider_name=provider or "openai",
                model=response.model,
                call_type="chat",
                prompt_tokens=usage_info.get("prompt_tokens"),
                completion_tokens=usage_info.get("completion_tokens"),
                request_id=getattr(request.state, "request_id", None),
            )
        # else: BYO - no deduction from our pool
    except Exception:
        pass

    return response


@router.post("/chat/stream")
async def chat_stream(
    request: Request,
    body: ChatCompletionRequest,
    user: Annotated[AuthUser, Depends(require_user)],
):
    """
    Streamed ReAct agent execution loop using Server-Sent Events (SSE).
    """
    import asyncio
    import json
    from fastapi.responses import StreamingResponse

    await enforce_rate_limit(request, user.id, user.plan)

    use_personal = bool(body.use_personal_llm)
    provider = body.llm_provider

    supabase = get_supabase_service()
    personal = await supabase.get_user_personal_key(user.id, provider) if use_personal else None
    using_platform = not personal

    if using_platform and not settings.llm_stub:
        if not await supabase.has_sufficient_credits(user.id, 1):
            raise HTTPException(
                status_code=402,
                detail="Insufficient platform credits. Buy more tokens or configure your own LLM keys.",
            )

    async def sse_generator():
        queue: asyncio.Queue = asyncio.Queue()

        def callback(event: dict[str, Any]):
            queue.put_nowait(event)

        async def async_generate_fn(history: list[dict[str, str]]) -> str:
            from ..models import ChatMessage
            req_messages = [ChatMessage(role=m["role"], content=m["content"]) for m in history]
            cloned_req = body.model_copy(update={"messages": req_messages})
            res = await complete_chat(
                cloned_req,
                user_id=user.id,
                provider=provider,
                use_personal=use_personal,
                model_override=body.model,
            )
            return res.message.content

        from matemium.agent.react_runner import ReActAgentRunner
        runner = ReActAgentRunner()

        user_prompt = body.messages[-1].content if body.messages else "Please refactor my scenes.py file"

        project_dir = None
        if body.project_id:
            from matemium.paths import discover_root
            project_dir = str(discover_root() / "projects" / body.project_id)

        async def run_runner_task():
            try:
                await runner.run_loop_async(
                    user_prompt=user_prompt,
                    generate_fn=async_generate_fn,
                    project_dir=project_dir,
                    callback=callback,
                )
            except Exception as e:
                queue.put_nowait({"type": "error", "message": str(e)})
            finally:
                queue.put_nowait(None)

            try:
                await supabase.increment_ai_calls(user.id, 1)
            except Exception:
                pass

        task = asyncio.create_task(run_runner_task())

        while True:
            event = await queue.get()
            if event is None:
                break
            yield f"data: {json.dumps(event)}\n\n"

        await task

    return StreamingResponse(sse_generator(), media_type="text/event-stream")